apiVersion: apps/v1
kind: Deployment
metadata:
  name: miqscraper
spec:
  selector:
    matchLabels:
      app: miqscraper
  replicas: 1
  template:
    metadata:
      labels:
        app: miqscraper
    spec:
      containers:
        - name: miqscraper
          image: edwardkcyu/miqscraper:latest
          imagePullPolicy: Always
          env:
            - name: MIQ_PORTAL_URL
              value: $MIQ_PORTAL_URL
            - name: SLACK_API_URL
              value: $SLACK_API_URL
            - name: SLACK_API_TOKEN
              value: $SLACK_API_TOKEN
            - name: SLACK_CHANNEL_NAME
              value: $SLACK_CHANNEL_NAME
            - name: SLACK_TARGET_CHANNEL_NAME
              value: $SLACK_TARGET_CHANNEL_NAME
