apiVersion: apps/v1
kind: Deployment
metadata:
  name: miqscraper
spec:
  selector:
    matchLabels:
      app: miqscraper
  replicas: 1
  template:
    metadata:
      labels:
        app: miqscraper
    spec:
      containers:
        - name: container
          image: k8s.gcr.io/busybox
          command: [ "/bin/sh", "-c", "env && echo && tail -f /dev/null" ]
          env:
            - name: MIQ_PORTAL_URL
              value: $MIQ_PORTAL_URL
