apiVersion: apps/v1
kind: Deployment
metadata:
  name: miqscraper
spec:
  selector:
    matchLabels:
      app: miqscraper
  replicas: 1
  template:
    metadata:
      labels:
        app: miqscraper
    spec:
      containers:
        - name: miqscraper
          image: edwardkcyu/miqscraper:latest